[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "dredge"
version = "26.03"
dependencies = [
    "numpy>=2",
]
authors = [
    {name = "Aaron Tran", email = "atran@physics.wisc.edu"},
]
description = "Dispersion relation solver for edge plasmas"
readme = "README.md"
requires-python = ">3"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

# following
# https://packaging.python.org/en/latest/tutorials/packaging-projects/
# https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages
